//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_EF.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BCMYEntities : DbContext
    {
        public BCMYEntities()
            : base("name=BCMYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vProductInfo> vProductInfoes { get; set; }
        public virtual DbSet<productbrand> productbrands { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<productCondition> productConditions { get; set; }
        public virtual DbSet<productlist> productlists { get; set; }
        public virtual DbSet<productprice> productprices { get; set; }
    
        public virtual ObjectResult<string> SP_GetDistinctProductModels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetDistinctProductModels");
        }
    }
}
