//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_EF.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class productprice
    {
        public int productpriceid { get; set; }
        public int productlistid { get; set; }
        public decimal marketvalue { get; set; }
        public decimal returnvalue { get; set; }
        public int pricelistID { get; set; }
    
        public virtual productlist productlist { get; set; }
    }
}
