//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_EF.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomerSupplier
    {
        public TblCustomerSupplier()
        {
            this.TblContacts = new HashSet<TblContact>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string addressLine3 { get; set; }
        public string town { get; set; }
        public string county { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string telephone { get; set; }
        public string bank { get; set; }
        public string vatNumber { get; set; }
        public string accountNumber { get; set; }
        public string sortcode { get; set; }
        public string iban { get; set; }
        public string swift { get; set; }
        public System.DateTime creationDateTime { get; set; }
        public Nullable<System.DateTime> inactiveDateTime { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<TblContact> TblContacts { get; set; }
    }
}
