//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_EF.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrder
    {
        public TblOrder()
        {
            this.TblNegotiations = new HashSet<TblNegotiation>();
            this.TblOrderLines = new HashSet<TblOrderLine>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> contactId { get; set; }
        public System.DateTime creationDateTime { get; set; }
    
        public virtual TblContact TblContact { get; set; }
        public virtual ICollection<TblNegotiation> TblNegotiations { get; set; }
        public virtual ICollection<TblOrderLine> TblOrderLines { get; set; }
    }
}
